### ISSUE TITLE
Retorno Vazio

### ISSUE THREAD

**Issue by CleisonPaiva** [fabioserpa/CNPJ-full#12]
(base) Mesa-Luciano:CNPJ-full-mastedr Fagner$ python3 cnpj.py "/Users/jonatas/Desktop/CNPJ-full-mastedr/dados.zip" csv "data"
Iniciando processamento em 2019-06-25 10:25:43.261103
Processando arquivo: /Users/jonatas/Desktop/CNPJ-full-mastedr/dados.zip
Processando bloco 1: até linha 200000.
Conversao concluida. Validando quantidades:
Total de registros de empresas: 0 ok
Total de registros de socios: 0 ok
Total de registros de CNAEs: 0 ok
Arquivos CSV gerados na pasta data.
Processamento concluido em 2019-06-25 10:25:43.275502

Saberia me informar o por que isso ocorre?Ele cria mas vem vazio

**Comment by fabioserpa** [comment]
Poderia descrever esse dados.zip? De onde baixou? Quando? Qual é o tamanho do arquivo?

**Comment by CleisonPaiva** [comment]
Eu tentei rodar no terminal fazendo *python3 cnpj.py "data\DADOS_ABERTOS_CNPJ.zip" csv "data"* ai da isso *No such file or directory: 'data\\DADOS_ABERTOS_CNPJ.zip'*,entao eu eu criei esse zip dados.zip no diretorio do projeto e ele roda e traz a mensagem informada na primeira pergunta que eu fiz.

**Comment by fabioserpa** [comment]
Mas você criou um arquivo vazio? O script apenas converte os dados disponobilizados pela Receita, então você vai precisar baixar os 6gb de arquivo do site da Receita.

**Comment by fabioserpa** [comment]
Atualmente a RF disponibilizou dividindo em varios zips, então a melhor forma de usar o script é baixando os zips para uma pasta, especificando essa pasta como parâmetro e usando a opção —dir

**Comment by CleisonPaiva** [comment]
![Captura de Tela 2019-06-25 às 11 04 26](https://user-images.githubusercontent.com/25806538/60105082-0edff880-9739-11e9-8f5a-ac29744aec52.png)


Fazendo simplismente isso essa pasta output e criada sem nada,no caso qual seria o proximo passo entao?

**Comment by CleisonPaiva** [comment]
Eu creio que entendi,eu devo baixar esses arquivos http://receita.economia.gov.br/orientacao/tributaria/cadastros/cadastro-nacional-de-pessoas-juridicas-cnpj/dados-publicos-cnpj  ,qualquel duvida eu volto a entrar em contato.Obrigado pela atencao!!

**Comment by CleisonPaiva** [comment]
python3 cnpj.py "/Users/jonatas/Desktop/past/DADOS_ABERTOS_CNPJ_01.zip" csv "data"
Iniciando processamento em 2019-06-26 13:49:52.090169
Processando arquivo: /Users/jonatas/Desktop/past/DADOS_ABERTOS_CNPJ_01.zip
Processando bloco 1: até linha 200000.
INFORMACOES DO HEADER:
Nome do arquivo: F.K032001K
Data de gravacao: 20190514
Numero da remessa: 00000001
Processando bloco 21: até linha 4200000.
Conversao concluida. Validando quantidades:
Total de registros de empresas: 1893562 !INCONSISTENTE!
Total de registros de socios: 1783932 !INCONSISTENTE!
Total de registros de CNAEs: 476200 !INCONSISTENTE!
Atencao! Foi detectada inconsistencia entre as quantidades lidas e as informacoes de controle do arquivo.
Arquivos CSV gerados na pasta data.




Oque seria essa inconsistencia que ocorre??
e quando eu executar  *python3 cnpj.py "/Users/jonatas/Desktop/past/DADOS_ABERTOS_CNPJ_02.zip" csv "data"*  no segundo zip ele ira substituir o primeiro?

**Comment by fabioserpa** [comment]
@Cleisonucl, como são múltiplos arquivos zip, você deve colocar todos em uma mesma pasta, e somente eles, e usar o script assim (considerando que os zips estão dentro dessa "past"):
python3 cnpj.py "/Users/jonatas/Desktop/past" csv "data" --dir

**Comment by CleisonPaiva** [comment]
entendi,funcionou
