### ISSUE TITLE
Divisão por UF

### ISSUE THREAD

**Issue by MallonMafra** [fabioserpa/CNPJ-full#13]
Esta ocorrendo erro ao separar .csv  por UF, no arquivo ".env.example" eu deixei desta forma:
"FILES_LOCATION=/output/"
"FILES_LOCATION=/output"

No meu computador o arquivo esta na pasta "C:\Users\meunome\AppData\Local\Programs\Python\Python37-32\output\empresas.csv"

ERRO: ("Traceback (most recent call last):
  File "separar_csv_por_uf.py", line 10, in <module>
    with codecs.open(location + file, 'r+', 'utf-8') as empresas:
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

Não sei oque pode ser, pode me ajudar?

**Comment by goncalvl** [comment]
Boa noite. Também estou enfrentando a mesma dificuldade. Alguém pode ajudar?

**Comment by gabismore** [comment]
Na parte do código "file = 'empresas.csv'", basta acrescentar um \ antes do empresas.csv: 
file = '\empresas.csv', pois quando rodava o programa ele não conseguia acesso ao documento ai não tinha nada dentro do "FILES_LOCATION" só isso resolve o problema

**Comment by goncalvl** [comment]
Bom dia. Gabismore, eu fiz o que você indicou, porém ainda continua o mesmo erro. No FILES_LOCATION já coloquei o caminho da pasta tanto com o \ e / (das formas), mas me parece que o script está com erro (with codecs.open(location + file, 'r+', 'utf-8') as empresas).

**Comment by gabismore** [comment]
desculpe faltou um passo que eu esqueci de falar, o arquivo .env.example não devia ter esse example ali
você deve converter esse .example para .env
para fazer essa conversão você deve 
1-abrir o prompt de comando 
2- digite [ cd ];
3- Copie e cole o endereço do arquivo(local onde está o arquivo .env.example)
5- Digite [ ren ] o nome ".env.example" atual do arquivo e o novo nome ".env" 
faça isso e coloque o ' \ ' antes do "empresas.csv" agora sim deve funcionar

**Comment by goncalvl** [comment]
Funcionou perfeitamente. Muito obrigado pela ajuda.

**Comment by MallonMafra** [comment]
Aqui também funcionou perfeitamente, Muito Obrigado pela Ajuda!
