### ISSUE TITLE
O script retorna um resultado vazio

### ISSUE THREAD

**Issue by Guiba26** [fabioserpa/CNPJ-full#16]
Recentemente a Receita Federal liberou uma nova versão dos dados públicos CNPJ (07/ago/2019). Baixei os arquivos e extraí todos, gerando 20 arquivos de 5.08Gb cada, porém, quando rodo o script cnpj.py, especificando o caminho de entrada e saída, o resultado retornado é:
> Total de registros de empresas: 0 ok
> Total de registros de socios: 0 ok
> Total de registros de CNAEs: 0 ok

Alguém também está enfrentando este problema com o novo arquivo?

**Comment by fabioserpa** [comment]
Não extraia previamente os arquivos. O script está preparado para processar diretamente os zips no diretório.

**Comment by fabioserpa** [comment]
De qualquer modo, acabei de atualizar o script para, se não encontrar arquivos zip na pasta, tentar ler os arquivos descompactados. Se não achar nada, interrompe e apresenta mensagem de erro.
