### ISSUE TITLE
Nao foi possivel encontrar ou conectar ao BD - Uso windows e não consigo acessar o banco

### ISSUE THREAD

**Issue by kpedrok** [fabioserpa/CNPJ-full#17]
Alguém sabe o que devo fazer?
![image](https://user-images.githubusercontent.com/43593052/64497302-46b00400-d283-11e9-8251-ccf15d9decc0.png)

**Comment by alanpereiracoelho** [comment]
Boa tarde, tem que informa o caminho completo para o BD 
Ex.: python3 consulta.py cnpj 68134000144  /mnt/c/CNPJ-full-master/dados_sql --base /mnt/c/CNPJ-full-master/dados_sql/CNPJ_full.db --graphml --viz

**Comment by fabioserpa** [comment]
Conseguiu resolver? Você deve seguir a sugestão acima ou preferencialmente configurar o caminho do arquivo SQLite (convertido pelo cnpj.py anteriormente) no config.py
