### ISSUE TITLE
Dados Públicos CNPJ - Conversão para CSV/SQLITE e Consultas

### ISSUE THREAD

**Issue by alanpereiracoelho** [fabioserpa/CNPJ-full#18]
Boa tarde, parabéns ao desenvolvedores muito bacana a ideia, consegui rodar aqui de boa no entanto quando faço a consulta ele gera o Gráfico abro no navegador mais não aparece as informações da empresa como na documentação aparece um Quadro preto junto ao Gráfico com os dados da empresa... Alguém pode me ajudar? Só aparece o nome dos sócios ligado um ponto ao outro!

**Comment by fabioserpa** [comment]
O quadro preto deveria aparecer quando passa o mouse por cima de uma empresa. Não está aparecendo?
