### ISSUE TITLE
Arquivos CSV dump

### ISSUE THREAD

**Issue by JoaoCarabetta** [fabioserpa/CNPJ-full#20]
Olá,

vocês tem os arquivos após tratamento disponíveis para download?

Não estou conseguindo baixar os dados da receita para processar com o pacote de vocês.

Valeu :)

**Comment by hsxavier** [comment]
Pra mim, os dados da receita demoram pelo menos uma hora pra começar o download, mas depois são baixados. 

Fora isso, essa base parece estar disponível aqui: https://brasil.io/dataset/socios-brasil/socios

Veja o link "baixar o dataset completo" no final da página.
