### ISSUE TITLE
A base de dados atual esta bem menor, alguém pode disponibilizar a base antiga no megaupload?

### ISSUE THREAD

**Issue by petkovic43** [fabioserpa/CNPJ-full#24]
A base atual está com certa de 6GB. Gostaria de saber se alguém tem a base antiga, com cerca de 40 milhões de CNPJs, e que possa disponibilizá-la em algum site como o megaupload ou google drive.

**Comment by ograndegio** [comment]
Bom dia,
Eu baixei esses arquivos disponibilizados pela RFB e eles possuem bem mais que 6GB (São 20 arquivos cada um em média com 5GB). Acredito que seja a base completa que você procura.
http://receita.economia.gov.br/orientacao/tributaria/cadastros/cadastro-nacional-de-pessoas-juridicas-cnpj/dados-publicos-cnpj

**Comment by fabioserpa** [comment]
A base anterior tinha aproximadamente 5,2 gb, ao invés dos 6 gb atuais. Não acho que seja uma diferença que faça valer a pena baixar uma base desatualizada, concorda?

**Comment by fabioserpa** [comment]
Os arquivos baixados, SE descompactador, ficam com Aprox. 90 gb. Repara que atualmente não é necessário descompactar o arquivo para a conversão. O próprio script lida diretamente com os arquivos zipados
