### ISSUE TITLE
Erro no separar_csv_por_uf.py

### ISSUE THREAD

**Issue by williamwaillant** [fabioserpa/CNPJ-full#26]
O código para separar por uf o csv, não está pegando a ultima linha do csv, fiz uns testes com um csv menor e todos deram o mesmo erro.

**Comment by andreturetta-brazil** [comment]
Estou com problemas para separar por uf no windows. 

_> python separar_csv_por_uf.py
  File "separar_csv_por_uf.py", line 5
    location = os.getenv('LOCATION_PATH=C:\Users\USER\Downloads\CNPJS\saida')
                         ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 16-17: truncated \UXXXXXXXX escape

**Comment by andreturetta-brazil** [comment]
Solução pro bug no windows acima, alterar a linha location no arquivo py:

location = r'C:\\Users\\USER\\Downloads\\CNPJS\\saida\\'

file = 'empresas.csv'

**Comment by williamwaillant** [comment]
Aham eu tive esse erro tb. Precisei colocar todas os diretórios manualmente
