### ISSUE TITLE
Atualização trimestral Nov/19

### ISSUE THREAD

**Issue by rodrigopmsilva** [fabioserpa/CNPJ-full#27]
Boa Noite! Alguém tem informações se a receita irá atualizar a base esse mês? Geralmente eles atualizam com 3 meses, mas até agora nada.

**Comment by Bothrel** [comment]
Foi atualizada dia 11/11/2019.

**Comment by andreturetta-brazil** [comment]
Pessoal uma dúvida de newbie... a cada atualizacao temos que baixar todos os zips novamente ou apenas o 20? que servicos de BD em cloud voces indicam para armazenamento e ETL..? abs

**Comment by rodrigopmsilva** [comment]
Para atualizar todas as empresas, é necessário baixar td ( pode haver encerramento das atividades, alterações de endereço e Razão Social...).

Caso queira atualizar somente as empresas abertas entre a atualização de agosto e a última atualização, é necessário baixar somente os arquivos 17 e 18.

**Comment by andreturetta-brazil** [comment]
Obrigadíssimo pelas informações Rodrigo! como estou tratando os dados localmente estou bem limitado pra analisar o comportamento dos arquivos... so confirmando, apenas o 17 e 18 ou do 17 pra frente (tem ate o 20 atualmente no site). abraços!

**Comment by rodrigopmsilva** [comment]
Os CNPJs abertos nesses período estão  nos arquivos 17 e 18 somente.

**Comment by fabioserpa** [comment]
De onde vem essa informação, @rodrigopmsilva ? Eu desconhecia, e considerava que a RF fazia um dump completo da base e por questões de lentidão do site passou a fatiar o arquivo em 20 arquivos. Parece-me, por exemplo, que se novos sócios são adicionados a empresas que estão nos primeiros arquivos, eles são inseridos juntos aos demais sócios daquelas empresas, "empurrando" os demais registros para "baixo". Não confirmei se a lógica é essa, mas fiquei curioso para saber de onde vem essa informação de que novas empresas estão sempre nos arquivos 17 e 18.

**Comment by fabioserpa** [comment]
E nesse caso esses arquivos teriam APENAS empresas abertas no período?

**Comment by rodrigopmsilva** [comment]
@fabioserpa, sim a RF faz isso. Mas atualmente a RF organiza os CNPJs por ordem crescente de numeração Raiz (8 primeiros números), logo observei que a faixa dos novos (abertos no período da atualização de agosto até essa última atualização ) CNPJs estão inseridos nós arquivos 17 e 18.

Entretanto, nesses arquivos há CNPJs criados há mais tempo também, pois no passado cada órgão estadual recebia da RF uma faixa de CNPJ para atribuição as novas solicitações de CNPJ.

Obs.: Essa lógica não serve para CNPJs de Filiais, visto que o número raiz foi atribuído no momento da abertura da Matriz.
