### ISSUE TITLE
Sistema de Consulta Web

### ISSUE THREAD

**Issue by bjverde** [fabioserpa/CNPJ-full#32]
Pessoal, 

Baseado no resultado do CNPJ-full, estou construido um sistema de consulta na web. A ideia é quem tenha um tela de consultas rápidas e fáceis. Incluído a ideia de gerar o Grafo. No momento ainda está bem no início.

Site do projeto https://github.com/bjverde/cnpjrfb

![Tela de Exemplo](https://github.com/bjverde/cnpjrfb/blob/master/www/cnpjrfb/app/images/tela_inicial.png?raw=true "Tela de Exemplo")

**Comment by LennonSantos** [comment]
vc poderia compartilhar a base de dados?

**Comment by bjverde** [comment]
> 
> vc poderia compartilhar a base de dados?

@LennonSantos , se entendi a sua pergunta a base de dados é aqui do projeto do [CNPJ-Full](https://github.com/fabioserpa/CNPJ-full) o que estou construindo é apenas um interface web para facilitar a consulta.

**Comment by fabioserpa** [comment]
Parabéns pela iniciativa!
