### ISSUE TITLE
CNPJ de ONG Faltando

### ISSUE THREAD

**Issue by fredroo** [fabioserpa/CNPJ-full#39]
Olá eu baixei os dados lá do site da Receita e usei o seu projeto para gerar o sqlite e depois converti em mysql

ao procurar o cnpj
https://cnpjs.rocks/cnpj/33915604000117/legiao-da-boa-vontade.html

não achei no banco

busquei usando nome, cnpj e até cnae

mas ai nesse cnpjs.rocks tem os dados

sabe me ajudar com isso Fabio @fabioserpa

**Comment by fabioserpa** [comment]
Não tenho a última versão da base de dados, mas procurei aqui pelo CNPJ na base SQLite gerada a partir da carga de 11/2019 e achou normalmente. Chegou a buscar diretamente na base SQLite?

**Comment by fredroo** [comment]
achou  mesmo no sqlite, vou ver se consigo converter para mysql sem perder nada

**Comment by fabioserpa** [comment]
Ok. Sugiro que logo após a carga sejam feitas algumas checagens básicas, como por exemplo comparar os totais de registros em casa tabela. Para analisar o conteúdo dos campos, algumas comparações de totais agrupados pelo conteúdo de alguns campos também ajudam (ex: contagem de registros de empresas por UF).
