### ISSUE TITLE
Suporte a outros bancos via SQLAlchemy

### ISSUE THREAD

**Issue by jonathands** [fabioserpa/CNPJ-full#40]
Gostaria de saber se existe o interesse adicionar suporte para outros bancos via SQLAlchemy?

Estou realizando alguns testes ref. a importação dos dados para PostgreSQL e verifiquei que é relativamente simples adicionar o suporte, porém não quero fazer PRs desnecessariamente.

**Comment by elossio** [comment]
Olá @jonathands, boa noite! Tenho interesse sim.

**Comment by fabioserpa** [comment]
Uma vez que não houve manifestação posterior nesta issue, vou fechá-la. Entendo que a questão é a mesma da issue "Utilização do SQLAlchemy".
