### ISSUE TITLE
Erro ao executar

### ISSUE THREAD

**Issue by ghost** [fabioserpa/CNPJ-full#43]
Não estou conseguindo executar o comando python3 cnpj.py <caminho entrada> <tipo de saída:csv ou sqlite> <pasta saída> --dir

Apresenta um erro de sintaxe:

python3 cnpj.py '/Dados_Públicos_Receita_Federal' csv '/analise_cnpj' --dir

File "<ipython-input-1-ecbc6506c2c7>", line 1
    python3 cnpj.py '/Dados_Públicos_Receita_Federal' csv '/analise_cnpj' --dir
                       ^
SyntaxError: invalid syntax

O jupyter notebook está aberto na pasta TI, 
Nesta pasta tem a pasta Dados_Publicos_Receita_Federal que informei acima e também nesta mesma pasta TI está a pasta de saída analise_cnpj.

Poderiam me ajudar?

Resolvido, faltou importar o código

**Comment by ggkf18** [comment]
@fabioserpa
