### ISSUE TITLE
Ponto e vírgula dentro de valores, interferindo na importação do csv com o pandas

### ISSUE THREAD

**Issue by brunocpradom** [fabioserpa/CNPJ-full#44]
Me deparei com um problema, ao importar o csv gerado pelo seu script com o módulo pandas. Mais especificamente , ao usar a função df.read_csv()  . Existem alguns valores dentro da coluna 'complemento' que tem um ponto e vírgula .
"LETRA:A;". 
              Mesmo eu estipulando o separador como uma vírgula, a função do pandas lê o ponto e vírgula como um separador , e cria um campo de valor vazio, comprometendo a legibilidade da tabela. Estou terminando um script  que faz algumas modificações na tabela , como substituir o número CNAE pelo seu significado,entre outros , e também de nomear as colunas. E depois manda tudo pra um banco de dados SQL. 
              Você acredita que seria possível inserir um código que identificasse quais strings tem um  ' ; ' ou até mesmo uma vírgula(poderia usar o REGEX) e a excluísse? Em quais dos arquivos poderia incluí-lo?

**Comment by elossio** [comment]
Prezado @brunocpradom, não só o ponto e vírgula mas outros caracteres, principalmente no conteúdo do campo razao_social, acabam prejudicando a importação do arquivo CSV para o banco de dados SQL. 

Consegui dividir o arquivo empresas.csv (mais de 43 milhões de CNPJ) por UF usando o script separar_csv_por_uf.py para reduzir o tamanho dos arquivos e poder trabalhar com algumas UF específicas. O processo de separação levou mais de 48 horas resultando 29 arquivos tipo CSV (27 das UF, socios.csv e cnaes_secundarios.csv). Minha ideia é copiar esses arquivos em tabelas de bancos de dados SQL. Devido ao problema de caracteres em alguns registros, não consegui usar o PostgreSQL. Neste instante, estou usando fazendo testes com o MySQL sem grandes surpresas.

Não cheguei a utilizar o script cnpj.py para geração de arquivo sqlite.

**Comment by brunocpradom** [comment]
Oi @elossio . Eu usei o script para converter para sqlite também.O arquivo fica com o tamanho de 20GB. Depois você pode importar o arquivo pro mysql. Usei o DBeaver pra fazer  as operações.   Mas o problema que tive foi ao importar os arquivos csv ( que gerei por município) com o panda (df.read_csv()  ).  Minha intenção é tratar esses dados para depois jogar no banco de dados.  Posso dizer que na maior parte das linhas, ficou como eu esperava, mas tem uma linha ou outra onde ocorre esse problema que citei acima.

**Comment by elossio** [comment]
Vou tentar a geração do arquivo SQLite usando a sua orientação.

Quanto aos caracteres estranhos na extração dos dados pelo Panda, consulte diretamente no site da Receita Federal se constam no cadastro do CNPJ estes caracteres. 

O correto seria o Panda considerar tudo entre os delimitadores, a vírgula no caso do CSV, pouco importando o conjunto de caracteres do campo texto. Pelo que informa no post, a restrição está na função do Panda.

Dependendo da sua necessidade, o saneamento dos dados pode ser efetuado em ferramentas específicas de ETL como o Power Query do Excel ou do Power BI.

**Comment by brunocpradom** [comment]
São muita planilhas . Uma pra cada município! 
Dei uma olhada nos arquivos da receita federal . Aparentemente não tem nenhum ponto e vírgula no meio dos dados. Talvez ele tenha sido gerado dentro do script do @fabioserpa  . 
Como são muitas linhas, fica difícil de saber com certeza.
