### ISSUE TITLE
Erro - WebSocketClosedError

### ISSUE THREAD

**Issue by ghost** [fabioserpa/CNPJ-full#45]
Estou com esse erro durante a execução da stream separar_csv_por_uf.py
Poderiam me ajudar?

![Capturar](https://user-images.githubusercontent.com/68596256/88054335-8eeeb280-cb33-11ea-8346-77ed36646628.PNG)

**Comment by fabioserpa** [comment]
Poderia mandar a mensagem de erro completa?

**Comment by fabioserpa** [comment]
Vou fechar essa issue, uma vez que não houve manifestação posterior.
