### ISSUE TITLE
Utilização do SQLAlchemy

### ISSUE THREAD

**Issue by faio** [fabioserpa/CNPJ-full#46]
Fiz um fork com uma implementação utilizando o SQLAlchemy, está disponível em https://github.com/faio/CNPJ-full caso queira que eu faça o PR é só me avisar, fiz também um utilitário para facilitar o download baixando em threads e todos de uma vez disponível em https://github.com/faio/receita-cnpj-download se tiver interesse em colocar no projeto

**Comment by fabioserpa** [comment]
@faio, legal, acho muito interessante a proposta de uso do SQLAlchemy e possibilidade de "converter" para outros tipos de BD.
Para incorporar ao projeto, no entanto, eu preferiria que fosse mantida a compatibilidade com a linha de comando original para quem sempre usou e pretende continuar usando SQLite.
Além disso, notei que quando se usa a opção database, o parâmetro obrigatório "path_output" parece ser inutilizado, ao mesmo tempo em que é necessário usar o parâmetro --database_url. Não seria melhor, ao invés desse parâmetro opcional, usar o parâmetro obrigatório de path_output como a url do database quando for essa a opção de output?

**Comment by fabioserpa** [comment]
@faio, quanto ao download, normalmente uso o aria2 como ferramenta, uma vez que permite otimizar tremendamente o download além de permitir a continuidade do download em caso de interrupção, algo indispensável para mim em uma época que minha internet caía muito frequentemente.
Mas acho legal sim incluir uma alternativa simples de automatização de download no próprio projeto. Quer fazer PR de inclusão do download.py?

**Comment by faio** [comment]
> @faio, legal, acho muito interessante a proposta de uso do SQLAlchemy e possibilidade de "converter" para outros tipos de BD.
> Para incorporar ao projeto, no entanto, eu preferiria que fosse mantida a compatibilidade com a linha de comando original para quem sempre usou e pretende continuar usando SQLite.
> Além disso, notei que quando se usa a opção database, o parâmetro obrigatório "path_output" parece ser inutilizado, ao mesmo tempo em que é necessário usar o parâmetro --database_url. Não seria melhor, ao invés desse parâmetro opcional, usar o parâmetro obrigatório de path_output como a url do database quando for essa a opção de output?

@fabioserpa desculpa man, eu acabei me perdendo aqui e não te respondi quando vi a sua mensagem estava ocupado e foi aquela de depois eu vejo e respondo e isso nunca chegou rsrsrs. Eu achei super interessante a sua sugestão, não tinha pensando nela, vou fazer aqui uma alteração já que eu preciso atualizar a base local nossa, vou ver se consigo rodar o processo em alguns bancos diferentes também para testarmos já que eu penso que pode ocorrer algum problema de carácter em alguns deles.

**Comment by faio** [comment]
> @faio, quanto ao download, normalmente uso o aria2 como ferramenta, uma vez que permite otimizar tremendamente o download além de permitir a continuidade do download em caso de interrupção, algo indispensável para mim em uma época que minha internet caía muito frequentemente.
> Mas acho legal sim incluir uma alternativa simples de automatização de download no próprio projeto. Quer fazer PR de inclusão do download.py?

Faço sim, vai ser uma honra ajudar o projeto que me economizou algumas boas horas de desenvolvimento, que fazer alguma sugestão ou posso adicionar o download e colocar apenas um novo parâmetro para caso o usuário queira ativar ou desativar o download?

Quando eu desenvolvi o utilitário eu ate pensei em utilizar o Aria2, tem um wrapper em python para o mesmo, mais eu pesei pelo fato de dependências, da forma que eu fiz a dependências de bibliotecas extras é 0, precisando apenas do bom e velho python com as suas libs e resolvendo pelo menos para min o problema de forma satisfatória.

**Comment by faio** [comment]
Fabio, fui olhar agora para começar a atualizar os dados da base e vi que foi alterado a disponibilização dos dados pela receita federal, acho que esse tópico ficou obsoleto, vou fechar o mesmo.
