### ISSUE TITLE
CNPJ que não existem

### ISSUE THREAD

**Issue by m41k31** [fabioserpa/CNPJ-full#47]
Boa tarde, consegui extrair tudo usando os .zip atualizados do site da receita, o problema não é no script, mas com os dados da receita, pego por exemplo, CNPJ do mes de janeiro de 2020, nem todos estão na base pública da receita, mas se for no site da receita e consultar o CNPJ individual ele existe, alguém sabe de algo? de ter muitos cnjs que não tem na base ma existirem?

**Comment by fabioserpa** [comment]
Que opção de output está utilizando, csv ou SQLite? Desconheço casos de cnpjs não contemplados na base, a não ser por uma questão de timing de atualização mesmo. Se não for um problema para você, poderia dar um exemplo de CNPJ que não encontrou?

**Comment by elossio** [comment]
A menos que o CNPJ seja inválido, não existe a possibilidade de não ser localizado na base da Receita Federal. Se a inscrição cadastral for recente é possível que o arquivo ZIP do cadastro aberto esteja desatualizado.

**Comment by rafarui** [comment]
> Boa tarde, consegui extrair tudo usando os .zip atualizados do site da receita, o problema não é no script, mas com os dados da receita, pego por exemplo, CNPJ do mes de janeiro de 2020, nem todos estão na base pública da receita, mas se for no site da receita e consultar o CNPJ individual ele existe, alguém sabe de algo? de ter muitos cnjs que não tem na base ma existirem?

complementando a resposta do @elossio 

A base eh gerada de 3 em 3 meses pela receita, logo empresas criadas nesse periodo vc nao encontrara. Assim como qualquer updates relacionadas ao cnpj. e.g., se a empresa fechar no periodo, nao sabera.

**Comment by elossio** [comment]
Isso mesmo @rafarui. Qualquer registro novo ou alteração cadastral posterior à data da geração dos arquivos abertos só será possível de ser visualizado a partir da próxima atualização da base disponibilizada pela Receita Federal.

**Comment by fabioserpa** [comment]
Fechando essa issue, uma vez que não houve manifestação posterior sobre a questão.
