### ISSUE TITLE
Quantidade de linhas

### ISSUE THREAD

**Issue by renatofelixdev** [fabioserpa/CNPJ-full#5]
Fiz o processo apresentado no readme.

Porém a quantidade de linhas ficou divergente.

Empresas 19.651.677
Sócios 9.212.053
CNAES 21.852.345

Está correto?

**Comment by fabioserpa** [comment]
Aparentemente não. Poderia dar mais detalhes detalhes sobre o arquivo de entrada utilizado? Nome, tamanho do arquivo, etc. Qual tipo de output escolheu? O processamento concluiu com mensagem de sucesso?

**Comment by renatofelixdev** [comment]
Arquivo baixado: F.K032001K.D81106D (81gb)

Versão do python
Python 2.7.11
pip 18.0

Comando executados:
python -m pip install pandas
python -m pip install numpy
python -m pip install numexpr

python cnpj.py F.K032001K.D81106D csv "data"

Arquivos gerados:
![image](https://user-images.githubusercontent.com/23421105/54819597-252e7200-4c7b-11e9-9ca2-e43248ac18a8.png)

Importação para o banco
LOAD DATA LOCAL INFILE 'empresas.csv' INTO TABLE empresas
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"' 
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES

Quantidade de linhas após importação:
Empresas 19.651.677
Sócios 9.212.053
CNAES 21.852.345

O processamento concluiu com mensagem de sucesso? Sim.

**Comment by fabioserpa** [comment]
A RF disponibilizou nova versão (atualizada) do arquivo. Que tal verificar se essa vai processar corretamente? Vi que você indicou ter usado o python 2.7. Não seria o caso de tentar usar o python 3? Não testei o script com python 2.7, e pode ser que ele tenha algumas questões, como por exemplo com encoding dos arquivos.

**Comment by carlosavf** [comment]
Boa noite. Primeiramente gostaria de agradecer pelo esforço. Mas verificando o registro de trailler, não bate com o numero de linhas gerado. Poderia verificar, pode ser que esteja com algum problema no processamento.

**Comment by fabioserpa** [comment]
@carlosavf, poderia detalhar melhor o seu cenário? Qual foi a versão do arquivo baixado da RF (informe o nome do arquivo, por favor)? Tentou a conversão para csv ou para sqlite? De que forma está contabilizando o número de linhas gerado? O número de linhas não está batendo para nenhuma das três tabelas? Repare apenas que a quantidade de linhas geradas para a tabela cnaes_secundarios não vai bater mesmo com a informação no trailler, uma vez que no arquivo original todos os CNAEs secundários de uma empresa estão em uma mesma linha, enquanto na conversão para csv/sqlite, é gerada uma linha para cada cnae secundário da empresa. As demais tabelas (empresas e socios) deveriam bater sim. Aqui para mim bateram: na versão publicada recentemente (F.K032001K.D90308) são 40.184.161 empresas e 18.613.392 registros de sócios. A tabela de cnaes_secundarios ficou com 45.321.058 registros de CNAEs secundários.

**Comment by carlosavf** [comment]
Boa tarde, Fábio.
Estou realizando a carga com o arquivo atual da receita federal e a copia do seu script python. Seguem meus resultados. Fiz a execução para geração de CSV.
EmpresaTamanho tabela Big Query - 9,55 GBQuantidade de linhas - 39.238.927 
SocioTamanho tabela Big Query- 1,56GBQuantidade de linhas - 18.398.542 
CNAE_secundarioTamanho tabela Big Query - 1,14GBQuantidade de linhas - 43.680.905
    Em sexta-feira, 12 de abril de 2019 01:14:28 BRT, fabioserpa <notifications@github.com> escreveu:  
 
 
@carlosavf, poderia detalhar melhor o seu cenário? Qual foi a versão do arquivo baixado da RF (informe o nome do arquivo, por favor)? Tentou a conversão para csv ou para sqlite? De que forma está contabilizando o número de linhas gerado? O número de linhas não está batendo para nenhuma das três tabelas? Repare apenas que a quantidade de linhas geradas para a tabela cnaes_secundarios não vai bater mesmo com a informação no trailler, uma vez que no arquivo original todos os CNAEs secundários de uma empresa estão em uma mesma linha, enquanto na conversão para csv/sqlite, é gerada uma linha para cada cnae secundário da empresa. As demais tabelas (empresas e socios) deveriam bater sim. Aqui para mim bateram: na versão publicada recentemente (F.K032001K.D90308) são 40.184.161 empresas e 18.613.392 registros de sócios. A tabela de cnaes_secundarios ficou com 45.321.058 registros de CNAEs secundários.

**Comment by fabioserpa** [comment]
Não sei o que houve, mas as quantidades de linhas mencionadas na sua mensagem são exatamente as quantidades de linhas da versão anterior do arquivo disponibilizado pela RF. Qual o nome do arquivo utilizado e o tamanho em GB?

**Comment by carlosavf** [comment]
http://200.152.38.155/CNPJ/DADOS_ABERTOS_CNPJ.zip

Tamanho: 5.026.398 KB
Este seria o arquivo atual? Ele é de 20 de Novembro de 2018
Dados públicos CNPJ


| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Dados públicos CNPJ

Dados Públicos CNPJ
 |

 |

 |






    Em sexta-feira, 12 de abril de 2019 15:03:44 BRT, fabioserpa <notifications@github.com> escreveu:  
 
 
Não sei o que houve, mas as quantidades de linhas mencionadas na sua mensagem são exatamente as quantidades de linhas da versão anterior do arquivo disponibilizado pela RF. Qual o nome do arquivo utilizado e o tamanho em GB?

**Comment by fabioserpa** [comment]
Não, esta é a versão anterior, e a quantidade de linhas está correta. A versão mais atual foi gerada em março agora, e disponibilizada no site da RF no início de abril.

**Comment by carlosavf** [comment]
ok, muito obrigado!

    Em sexta-feira, 12 de abril de 2019 15:24:31 BRT, fabioserpa <notifications@github.com> escreveu:  
 
 
Não, esta é a versão anterior, e a quantidade de linhas está correta. A versão mais atual foi gerada em março agora, e disponibilizada no site da RF no início de abril.

**Comment by guilhermex88** [comment]
Olá @fabioserpa. Tudo bem? Esta versão nova que te refere é a completa (com CPF parcial?). Pelo numero de empresas, teria que ser pois a QSA "normal" omite todas MEI´s e EI. Onde que foi disponibilizada?
Estou trabalhando em montar uma solução de consulta para minimizar o estrago feito por estelionatários.  A saída de novembro permitiu descobrir que há uma quantidade enorme de calotes dados por "empresários" quem chegam a ter mais de 10 empresas falidas no CPF...

**Comment by fabioserpa** [comment]
Oi @guilhermex88, o script deste repositório se refere sempre à versão completa da base (com CPF parcialmente mascarado), que foi disponibilizada pela primeira vez em novembro/18. Na descrição do repositório há um link para a página da RF onde o arquivo foi disponibilizado. Quanto à "versão nova" a qual me referia nessa issue, se refere à atualização mais recente, de março/19. Apenas atualização de dados, sem mudança de estrutura, ok?

**Comment by crashstz** [comment]
Olá @fabioserpa, fiz o processo e o arquivo scv gerado também deu divergência das linhas

Arquivo compactado 5.4 GB
Arquivo F.K032001K.D90308 com 88.9 GB

CSVs:
Empresas: 165,9mb (605.574 linhas)
Sócios: 31mb (275.404 linhas)

Estou utilizando o Linux Ubuntu em uma máquina virtual, será que o processo é interrompido por alguma questão do sistema linux ou configuração de hardware ou no download ou exportação o arquivo pode ter sido corrompido?

A extrutura do arquivo em DB são as 3 planilhas juntas? Ele gerado fica com quantos gigas?

**Comment by crashstz** [comment]
Olá @fabioserpa , fiz o processo e o arquivo scv gerado também deu divergência das linhas

$ python3 --version
Python 3.6.7

Arquivo compactado 5.4 GB
Arquivo F.K032001K.D90308 com 88.9 GB

CSVs:
Empresas: 165,9mb (605.574 linhas)
Sócios: 31mb (275.404 linhas)
E o processamento concluiu com mensagem de sucesso!
<img src="https://i.imgur.com/DHx5y33.png" alt="image" style="max-width:100%;"></a></p>

Estou utilizando o Linux Ubuntu em uma máquina virtual, será que o processo é interrompido por alguma questão do sistema linux ou configuração de hardware!? Ou é mais provável que no download ou exportação o arquivo tenha sido corrompido?

A extrutura do arquivo em DB são as 3 planilhas juntas? Ele gerado fica com quantos gigas?

Para evitar erros, existe uma forma ideal de baixar o arquivo do site da Receita?

@fabioserpa você faz trabalho de Freelancer? Se sim, me passa seu contato, por favor.

**Comment by fabioserpa** [comment]
Curioso, pois realmente ele vai até o bloco 10 e termina normalmente, quando na verdade essa versão do arquivo tem mais de 740 blocos. Como se a função de leitura estivesse com um parâmetro de limite de linha definido. Que versão da biblioteca **pandas** você tem em seu ambiente? Acho dificil um arquivo corrompido ou cortado dezipar em um arquivo consistente o suficiente para não disparar erro na leitura. O BD gerado é um arquivo sqlite, que pode ser aberto com ferramentas como o SQLite Studio e funcionam como um cliente de SGBDs, permitindo fazer queries SQL. É sem dúvida a forma mais rápida e prática de usar os dados. A ideia de disponibilizar versão em csv é permitir a carga em SGBDs, e não para consumo direto, pois os arquivos são muito grandes.

**Comment by fabioserpa** [comment]
Subi uma nova versão do cnpj.py que suporta uma aparentemente mudança de padrão no arquivo novo da RF, e aproveitei para aprimorar o processamento para imprimir as informações das linhas de header e trailler, além de contabilizar as linhas e confrontá-las com as informações de controle no trailler, dando mais segurança se o arquivo foi completamente convertido.

**Comment by macmacard** [comment]
Olá Fábio! Belo código! Parabéns! 
Estou entrando em Python agora e tenho algumas dúvidas...
Fiz download de 2 arquivos, montei o Anaconda e executei a geração. 
Gerei o SQLite e tudo bem! 
Mas não entendi, ou melhor não sei como fazer essa parte "Para ambos os scripts é necessário informar a localização do arquivo empresas.csv no arquivo .env
FILES_LOCATION=/media/Arquivos"...
Como faço isso, me desculpe por te incomodar!
desde já agradeço sua compreensão.
