### ISSUE TITLE
Organizar visualização no viz em html

### ISSUE THREAD

**Issue by hugonbgg** [fabioserpa/CNPJ-full#51]
É possível organizar a visualização de alguma maneira? por exemplo, em consultas do nivel 2 ou mais os sócios e empresas se sobrepõem e é dificil visualizar quem é quem, é preciso arrastar as "bolinhas" até que eles se auto organizem. 
Existe alguma maneira de agrupar os resultados automaticamente em torno dos sócios, por exemplo?
Agradeço desde já

**Comment by fabioserpa** [comment]
@hugonbgg, o recurso de visualização em HTML é um quebra-galho que de fato possui algumas limitações quando são apresentados grafos mais densos. Melhorar esse recurso provavelmente exigiria um esforço elevado e conhecimentos mais profundos da tecnologia D3. Como alternativa, é possível também gerar o grafo em arquivos que podem ser abertos em softwares especialistas, como o Gephi. Nesses softwares, é possível utilizar alguns recursos de organização automática do layout.
