### ISSUE TITLE
Gerando SQLite vazio

### ISSUE THREAD

**Issue by Alex-Basto** [fabioserpa/CNPJ-full#56]
Estou executando o script sem problemas, instalei todas as dependências, ele processa os arquivos sem exibir nenhum erro, porem esta gerando um arquivo .db sem dados

Finalização do Processo:
![Processo Finalizado](https://user-images.githubusercontent.com/52386938/137505890-9884d59e-31b1-433b-8add-cf8cf769abe4.PNG)

Arquivo gerado:
![Arquivo Final](https://user-images.githubusercontent.com/52386938/137505925-300c0764-7ee3-4839-804e-4ac6e604d142.PNG)

Alguém teve este problema ou sabe como resolver?
Obrigado!

**Comment by rictom** [comment]
O layout dos arquivos da receita mudou bastante em 2021. Antes os arquivos vinham em formato tsv com largura fixa de campos e agora em csv. O script cnpj_full não foi ajustado para o novo layout. 
Se vc quiser, testa o meu script https://github.com/rictom/cnpj-sqlite, que faz a geração de sqlite a partir dos zips.

**Comment by Alex-Basto** [comment]
Obrigado, seu script deu certinho, já criou o SQLite aqui, levou 1h e meia, comecei as 13:30 e finalizou agora as 14:58, agora trabalhar em cima dele, porem antes eu tive que instalar: 
DASK
`pip install dask`
 e 
SQLAlchemy 
`pip install SQLAlchemy`

ai rodou tudo certinho com Python 3.9

Muito Obrigado!!

**Comment by rictom** [comment]
Legal. Obrigado por testar!
