### ISSUE TITLE
Erro no zip

### ISSUE THREAD

**Issue by reichaves** [fabioserpa/CNPJ-full#7]
Olá
Por favor, o arquivo que baixo da Receita - DADOS_ABERTOS_CNPJ.zip
(5.147.030.696 bytes) - apresenta um erro quando descompacto - uso o
Peazip: ele não descompacta todo, mostra Erro fatal ocorreu em 3m57s -
podem estar bloqueados, não acessível ou corrompidos

No Terminal também: unzip DADOS_ABERTOS_CNPJ.zip
Archive:  DADOS_ABERTOS_CNPJ.zip
warning [DADOS_ABERTOS_CNPJ.zip]:  852063295 extra bytes at beginning or within zipfile
  (attempting to process anyway)
error [DADOS_ABERTOS_CNPJ.zip]:  start of central directory not found;
  zipfile corrupt.
  (please check that you have transferred or created the zipfile in the
  appropriate BINARY mode and that you have compiled UnZip properly)

Você também teve esse erro?

Parabéns pela iniciativa!

Abraço

**Comment by fabioserpa** [comment]
Não tive esse problema, nem soube de situação similar. Usei o 7-zip. Será que o arquivo baixou corrompido? Já tentou baixar novamente?

**Comment by fabioserpa** [comment]
A RF disponibilizou nesses dias (mais precisamente 3/abr) nova versão, atualizada, do arquivo. Que tal verificar se essa vai descomprimir sem trauma?

**Comment by reichaves** [comment]
Olá. Obrigado pelo aviso, vou baixar a nova versão

**Comment by reichaves** [comment]
Outro detalhe só para comentar, pelo menos aqui o download é muito lento, mais de seis horas. Não sei se isso também pode ajudar a corromper o arquivo também

**Comment by fabioserpa** [comment]
Em um teste recente com a versão anterior, ao dezipar usando o 7-zip, percebi que o programa dava um "warning" sobre alguma inconsistência, apesar de ao final descompactar numa boa. Mas não sei se era isso que fazia com que suas tentativas de descompressão falhassem. De qualquer forma, acabei de concluir o download da versão nova (levou mais de 24 horas o download), vi que essa não está gerando warning, então há uma boa perspectiva para você.

**Comment by PimentelRodrigo** [comment]
Fabio tudo bom ?
Tentei descompactar o arquivo e ao final ele aparece corrompido.... baixei 3 vezes e alguns amigos também tentaram, estamos fazendo um projeto para a faculdade. Por acaso vc baixou a versão do dia 24 de maio e tentou extrair ?

**Comment by fabioserpa** [comment]
@PimentelRodrigo, infelizmente ainda não consegui baixar a versão de maio. O download está mais lento do que nunca. Ainda não tive relatos de downloads e cargas bem sucedidas.

**Comment by BaiterYamato** [comment]
ocorrendo o mesmo problema, porém tenho um link mirror com o download mais rápido
https://data.brasil.io/mirror/socios-brasil/DADOS_ABERTOS_CNPJ.zip

**Comment by fabioserpa** [comment]
Subi uma nova versão do cnpj.py sem a conversão dessas colunas para float, e aproveitei para aprimorar o processamento para imprimir as informações das linhas de header e trailler, além de contabilizar as linhas e confrontá-las com as informações de controle no trailler, dando mais segurança se o arquivo foi completamente convertido.

**Comment by fabioserpa** [comment]
@baiter12, esse link mirror é para a versão de maio mesmo? Como é possível confirmar isso sem ter de baixar?
